# Generated by Django 3.2.10 on 2021-12-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dep', models.CharField(max_length=100)),
                ('salary', models.IntegerField(max_length=12)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
